services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - login-network
  app:
    build:
      context: .
    restart: always
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - login-network

networks:
  login-network:
    driver: bridge